### ISSUE TITLE
option to tag untagged images

### ISSUE THREAD

**Issue by mortya** [redhat-cop/openshift-disconnected-operators#20]
Many of the images copied by openshift-disconnected-operators are specified and copied by SHA256 digest rather than by tag.  This can be a problem for gitlab container registries.  Could we have an option to generate a tag for such registries?  Thanks!

**Comment by mortya** [comment]
Note that I've written the code to do this.  But it's relative to my old pull request #18, which isn't merged yet.  So probably cleaner to wait for the disposition on that one.

**Comment by mortya** [comment]
I've submitted pull request #22  for this.  Or if  you accept my earlier pull request #18 , let me know, and I can submit a new pull request relative to that one to save you a little merge trouble.

**Comment by arvin-a** [comment]
PR merged
